import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarLeft from "@/components/sidebar-left";
import SidebarRight from "@/components/sidebar-right";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex justify-between bg-zinc-100 gap-5 max-lg:flex-col">
        <SidebarLeft />
        <main className="w-full lg:max-w-200 min-h-dvh shrink overflow-hidden max-lg:pt-18 max-lg:pb-20">
          {children}
        </main>
        <SidebarRight />
      </body>
    </html>
  );
}
